[package]
name = "d_lsp"
version = "0.1.0"
edition = "2021"

[dependencies]
d_compiler = { path = "../compiler" }
lsp-server = "0.7.6"
lsp-types = "0.95.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.120"
