[package]
name = "d_dap"
version = "0.1.0"
edition = "2021"

[dependencies]
d_compiler = { path = "../compiler" }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.120"
dap = "0.4.1-alpha1"
anyhow = "1.0.75"
